# Generated by ts2python version 0.8.2
# compatibility level: Python 3.14 and above



from typing import (
    List,
    Literal,
    NotRequired,
    Tuple,
    TypedDict,
)

source_hash__ = "fe6486c83cc7eeb79e383cef2bcc50ef"


##### BEGIN OF ts2python generated code



type AssignmentID = int

type DateString = str

type SRSID = int

type SubjectId = int

type SubjectType = Literal["kana_vocabulary", "kanji", "radical", "vocabulary"]

type WKLevel = int


class WKResponse(TypedDict):
    object: str
    url: str
    data_updated_at: DateString | None


class WKMeaning(TypedDict):
    meaning: str
    primary: bool
    accepted_answer: bool


class WKAuxMeaning(TypedDict):
    meaning: str
    type: Literal["whitelist", "blacklist"]


class WKReading(TypedDict):
    reading: str
    primary: bool
    accepted_answer: bool
    type: Literal["kunyomi", "nanori", "onyomi"]


class WKContextSentence(TypedDict):
    en: str
    ja: str


class WKAudioMetadata(TypedDict):
    gender: Literal["male", "female"]
    source_id: int
    pronunciation: str
    voice_actor_id: int
    voice_actor_name: str
    voice_description: str


class WKAudio(TypedDict):
    url: str
    content_type: str
    metadata: WKAudioMetadata


class WKSubjectDataBase(TypedDict):
    auxiliary_meanings: List[WKAuxMeaning]
    characters: str
    created_at: DateString
    document_url: str
    hidden_at: DateString | None
    lesson_position: int
    level: WKLevel
    meaning_mnemonic: str
    meanings: List[WKMeaning]
    slug: str
    spaced_repetition_system_id: SRSID


class WKReadable(TypedDict):
    readings: List[WKReading]


class WKComponentData(WKSubjectDataBase, TypedDict):
    amalgamation_subject_ids: List[SubjectId]


class WKAssignmentData(TypedDict):
    available_at: None | DateString
    burned_at: None | DateString
    created_at: DateString
    hidden: bool
    passed_at: None | DateString
    resurrected_at: None | DateString
    srs_stage: int
    started_at: None | DateString
    subject_id: int
    subject_type: SubjectType
    unlocked_at: None | DateString


class WKAssignment(WKResponse, TypedDict):
    id: AssignmentID
    data: WKAssignmentData


class WKAssignmentsResponse(WKResponse, TypedDict):
    data: List[WKAssignment]
    total_count: int


class WKStudyMaterialData(TypedDict):
    created_at: DateString
    hidden: bool
    meaning_note: str
    meaning_synonyms: List[str]
    reading_note: str
    subject_id: int
    subject_type: SubjectType


class WKStudyMaterial(WKResponse, TypedDict):
    data: WKStudyMaterialData


class WKStudyMaterialsResponse(WKResponse, TypedDict):
    data: List[WKStudyMaterial]
    total_count: int


class WKSubscription(TypedDict):
    active: bool
    max_level_granted: WKLevel
    period_ends_at: None | DateString
    type: Literal["free", "recurring", "lifetime"]


class WKPreferences(TypedDict):
    default_voice_actor_id: int
    extra_study_autoplay_audio: bool
    lessons_autoplay_audio: bool
    lessons_batch_size: int
    lessons_presentation_order: Literal["ascending_level_then_subject"]
    reviews_autoplay_audio: bool
    reviews_display_srs_indicator: bool
    reviews_presentation_order: Literal["shuffled", "lower_levels_first"]


class WKUserData(TypedDict):
    current_vacation_started_at: DateString | None
    level: WKLevel
    preferences: WKPreferences
    profile_url: str
    started_at: DateString
    subscription: WKSubscription
    username: str


class WKUser(WKResponse, TypedDict):
    data: WKUserData


class WKSRSStageBase(TypedDict):
    position: int


class WKSRSStageEmpty(WKSRSStageBase, TypedDict):
    interval: None
    interval_unit: None


class WKSRSStageNonEmpty(WKSRSStageBase, TypedDict):
    interval: int
    interval_unit: Literal[
        "milliseconds", "seconds", "minutes", "hours", "days", "weeks"
    ]


type WKSpacedRepetitionSystemStage = WKSRSStageNonEmpty | WKSRSStageEmpty


class WKSpacedRepetitionSystemData(TypedDict):
    burning_stage_position: int
    created_at: DateString
    description: str
    name: str
    passing_stage_position: int
    stages: List[WKSpacedRepetitionSystemStage]
    starting_stage_position: int
    unlocking_stage_position: int


class WKSpacedRepetitionSystem(WKResponse, TypedDict):
    data: WKSpacedRepetitionSystemData


class WKCharacterImageMetadata(TypedDict):
    inline_styles: NotRequired[bool]


class WKCharacterImage(TypedDict):
    url: str
    content_type: str
    metadata: WKCharacterImageMetadata


class WKRadicalData(WKComponentData, TypedDict):
    character_images: List[WKCharacterImage]


class WKAmalgumData(TypedDict):
    component_subject_ids: List[SubjectId]


class WKKanjiData(WKAmalgumData, WKComponentData, WKReadable, TypedDict):
    meaning_hint: str | None
    reading_hint: str | None
    reading_mnemonic: str
    visually_similar_subject_ids: List[SubjectId]


class WKVocabBase(WKSubjectDataBase, TypedDict):
    context_sentences: List[WKContextSentence]
    parts_of_speech: List[str]
    pronunciation_audios: List[WKAudio]


class WKVocabData(WKAmalgumData, WKVocabBase, WKReadable, TypedDict):
    reading_mnemonic: str


type WKKanaVocabData = WKVocabBase

type WKSubjectData = (
    WKKanaVocabData | WKKanjiData | WKRadicalData | WKSubjectDataBase | WKVocabData
)


class WKSubject(WKResponse, TypedDict):
    id: int
    data: WKSubjectData


class WKSubjectsResponse(WKResponse, TypedDict):
    data: List[WKSubject]
    total_count: int


class RelatedSubject(TypedDict):
    characters: str
    reading: str
    meaning: str


class KeiseiCompound(TypedDict):
    character: str
    reading: str
    meaning: str


class KeiseiJSON(TypedDict):
    compounds: NotRequired[List[KeiseiCompound]]
    component: NotRequired[str]
    kanji: NotRequired[Tuple[str, str]]
    radical: NotRequired[str]
    readings: NotRequired[List[str]]
    semantic: NotRequired[str]
    type: str


##### END OF ts2python generated code
